### ISSUE TITLE
When do we bump the version number?

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/kudos#12]
@Athas seems like you have strong feelings about this - do we bump it every week? Or is are KUDOS versions completely independent of OSM?

**Comment by athas** [comment]
Oleks notifications@github.com writes:

> @Athas seems like you have strong feelings about this - do we bump it
> every week? Or is are KUDOS versions completely independent of OSM?

Bump the version number whenever we hand out a KUDOS tarball.  No idea
how this is supposed to interact with assignment-specific handouts,
however.  Probably the base version number (which is then bumped)
followed by a tag.  E.g., the G2 handout would be
kudos-2-g2handout.tar.gz.

## 

\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Sat, Feb 20, 2016 at 12:55 PM, Troels Henriksen <notifications@github.com

> wrote:
> 
> Oleks notifications@github.com writes:
> 
> > @Athas seems like you have strong feelings about this - do we bump it
> > every week? Or is are KUDOS versions completely independent of OSM?
> 
> Bump the version number whenever we hand out a KUDOS tarball. No idea
> how this is supposed to interact with assignment-specific handouts,
> however. Probably the base version number (which is then bumped)
> followed by a tag. E.g., the G2 handout would be
> kudos-2-g2handout.tar.gz.

I like the idea that students (initially) only get exposed to the necessary
subset of the documentation, so I like the idea of having KUDOS docs v1,
KUDOS docs v2, etc. No idea (yet) how that will happen in the next
iteration of the course, so for now, I understand, that we just bump the
KUDOS (and docs) version number with every KUDOS handout, i.e. once a week.

**Comment by oleks** [comment]
Resolved.
