### ISSUE TITLE
Document the process start-up and give an introduction to processes in the docs

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/kudos#13]

**Comment by oleks** [comment]
Closed as of 78937540ebd36f53ef1472c111bebd778647f56c

**Comment by nicklaswj** [comment]
Hi.
Does this mean that someone has done my work, or is there something i'm
missing here?

@oleks

**Comment by oleks** [comment]
On Sun, Feb 21, 2016 at 2:01 PM, nicklaswj notifications@github.com wrote:

> Hi.
> Does this mean that someone has done my work, or is there something i'm
> missing here?

That's exactly right.

I mentioned @Athas commit
https://github.com/DIKU-EDU/kudos/commit/78937540ebd36f53ef1472c111bebd778647f56c
as I closed the issue.

I think this is what we talked about you were going to do?

**Comment by athas** [comment]
Oleks notifications@github.com writes:

> On Sun, Feb 21, 2016 at 2:01 PM, nicklaswj notifications@github.com wrote:
> 
> > Hi.
> > Does this mean that someone has done my work, or is there something i'm
> > missing here?
> 
> That's exactly right.

Well, I only wrote the bare minimum necessary for G2.  Further
documenting the details (and the launch of the initial process) may
still be worthwhile.

## 

\  Troels
/\ Henriksen
