### ISSUE TITLE
Add the -pedantic option to the KUDOS Makefile

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/kudos#18]
Currently it will complain about the interrupt setup code in `kernel/mips32/interrupt.c`.

**Comment by athas** [comment]
Do it!

**Comment by oleks** [comment]
On Tue, Feb 23, 2016 at 3:21 PM, Troels Henriksen
notifications@github.com wrote:

> Do it!

Troll?

**Comment by athas** [comment]
Oleks notifications@github.com writes:

> On Tue, Feb 23, 2016 at 3:21 PM, Troels Henriksen
> notifications@github.com wrote:
> 
> > Do it!
> 
> Troll?

You know it.

## 

\  Troels
/\ Henriksen
