### ISSUE TITLE
Conflicting term "modules"

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/kudos#29]
Issues are a great place for bikeshed-questions like this! Comment! Comment! Comment!

We have a notion of "kernel module", neatly corresponding to a directory in the source tree, but also a notion of "device module", corresponding to device drivers statically linked with the kernel, but only conditionally loaded at boot-time.

Both in some sense are "modules", but they work differently, and so, I believe, deserve different names.

@nicklaswj @Athas

**Comment by athas** [comment]
Oleks notifications@github.com writes:

> Issues are a great place for bikeshed-questions like this! Comment! Comment! Comment!
> 
> We have a notion of "kernel module", neatly corresponding to a
> directory in the source tree, but also a notion of "device module",
> corresponding to device drivers statically linked with the kernel, but
> only conditionally loaded at boot-time.
> 
> Both in some sense are "modules", but they work differently, and so, I
> believe, deserve different names.

It is bizarre to call the source directories "kernel modules" since they
are not, you know, modular at all.  They are subsystems, not modules.

There is no room for bikeshedding here, because I am right.

## 

\  Troels
/\ Henriksen

**Comment by oleks** [comment]
Aha, what I called "kernel modules" above are typically called subsystems. Also [in our own documentation](http://kudos.readthedocs.io/en/latest/bootstrapping-kudos.html#starting-subsystems). The reason I called them "modules" is because we have a `module.mk` defining each subsystem.

**Comment by athas** [comment]
Can we change the name of the `module.mk` files, or is it some make rule/convention?

**Comment by oleks** [comment]
[Yes we can](https://github.com/DIKU-EDU/kudos/blob/master/kudos/Makefile#L62). I'm not sure if it is a "convention" though.

**Comment by oleks** [comment]
The convention seems to come from [Recursive Make Considered Harmful](http://aegis.sourceforge.net/auug97.pdf): "This refers to the use of a hierarchy of directories containing source files for the modules which make up the project..."
