### ISSUE TITLE
Document what need be for implementing userland processes

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/kudos#3]
Minus system calls, I'll take care of that.

**Comment by athas** [comment]
Oleks notifications@github.com writes:

> Assigned #3 to @Athas.

How do you expect this to look?  It is an assignment, so surely I should
not show them the code?  The old Buenos docs did IIRC not document user
processes.

I guess what I am asking is this: will this piece of documentation be
distinct from the implementation hints/guide of G2, which is already my
responsibility?

## 

\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Sun, Feb 7, 2016 at 2:08 PM, Troels Henriksen notifications@github.com
wrote:

> Oleks notifications@github.com writes:
> 
> > Assigned #3 to @Athas.
> 
> How do you expect this to look? It is an assignment, so surely I should
> not show them the code? The old Buenos docs did IIRC not document user
> processes.
> 
> I guess what I am asking is this: will this piece of documentation be
> distinct from the implementation hints/guide of G2, which is already my
> responsibility?

I expect this to look like a quick translation of chapter 6, up to, but
excluding section 6.4.

**Comment by athas** [comment]
I did this.  Seems a bit scarce, but if it worked in previous years...
