### ISSUE TITLE
/* */ vs //

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/kudos#30]
Bikeshed!

**Comment by oleks** [comment]
For starters, I think we should remove [my earlier argument](https://github.com/DIKU-EDU/kudos/blame/master/STYLE.rst#L77) for preferring `//` over `/* */`. Relying on your text-editor to comment out with `//` is more robust. Maybe all comments should be `//`?

**Comment by athas** [comment]
Agreed, but mostly because C has stupid rules for block comments (they cannot be nested).
