### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by athas** [DIKU-EDU/kudos#5]
Let's get this one out of the way.  When we hand out Kudos to the students, I suppose we will do it in the form of a tarball.  The contents of this tarball will correspond to a specific Git commit, but commits are not nice version numbers as they are not ordered.  Invariably, we will want to make changes and hand out new tarballs (maybe not until next year, but who knows), so we do need some policy for assigning version numbers.

I suggest we do what everyone else is doing and start at version 1, then increment the number for every new  release.  Anything more complicated is pointless.  We will use Git tags (`v1`) to keep track of the version numbers in the repository.

**Comment by oleks** [comment]
On Sun, Feb 7, 2016 at 10:30 AM, Troels Henriksen notifications@github.com
wrote:

> Let's get this one out of the way. When we hand out Kudos to the students,
> I suppose we will do it in the form of a tarball. The contents of this
> tarball will correspond to a specific Git commit, but commits are not nice
> version numbers as they are not ordered. Invariably, we will want to make
> changes and hand out new tarballs (maybe not until next year, but who
> knows), so we do need some policy for assigning version numbers.
> 
> I suggest we do what everyone else is doing and start at version 1, then
> increment the number for every new release. Anything more complicated is
> pointless. We will use Git tags (v1) to keep track of the version numbers
> in the repository.
> 
> I agree, except that I think we should start at 2.0.0 and increment the
> last integer, so 2.0.1, 2.0.2, etc.

When we hand KUDOS out though I think we should call them G1-handout,
G2-handout, etc. without mentioning the version number to the students.

**Comment by athas** [comment]
Oleks notifications@github.com writes:

> I agree, except that I think we should start at 2.0.0 and increment the
> last integer, so 2.0.1, 2.0.2, etc.

Why?

## 

\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Sun, Feb 7, 2016 at 12:12 PM, Troels Henriksen notifications@github.com
wrote:

> Oleks notifications@github.com writes:
> 
> > I agree, except that I think we should start at 2.0.0 and increment the
> > last integer, so 2.0.1, 2.0.2, etc.
> 
> Why?

I just thought it was unfair to discard the fact that Buenos made it to
1.1.2.

But okay, new names demand new version numbers!

**Comment by oleks** [comment]
I have renamed the milestone to 1.0. Is this closed?

**Comment by athas** [comment]
Why the decimal?  Are we ever going to worry about breaking compatibility, and will our users worry about this?

**Comment by athas** [comment]
It is just a way for students to know whether they have the newest version.  Version numbers beyond that are redundant.

**Comment by oleks** [comment]
Done!
